import { FormEvent, useState } from 'react'
import { Annotation, JobDescription } from '../lib/api'
import { Check, ChevronUp, MessageSquare, Paperclip, Trash2 } from 'lucide'
import { MorphGlyph } from './MorphGlyph'
import { Button } from '@/components/ui/button'
import { Textarea } from '@/components/ui/textarea'

export default function Assistant({annotations,jobs,selection,onAnnotate,onResolve,onDelete,onAddJob}:{annotations:Annotation[];jobs:JobDescription[];selection:string;onAnnotate:(note:string)=>void;onResolve:(id:string)=>void;onDelete:(id:string)=>void;onAddJob:(value:{title:string;content:string}|File)=>void}){
  const [note,setNote]=useState(''); const [jobOpen,setJobOpen]=useState(false); const [job,setJob]=useState('');
  function submit(e:FormEvent){e.preventDefault();if(note.trim()){onAnnotate(note);setNote('')}}
  return <aside className="assistant"><header><p className="eyebrow">Review workspace</p><h2>Annotations</h2></header>{selection&&<section className="selection-card"><small>Selected text</small><p>“{selection}”</p><form onSubmit={submit}><Textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Add a note or change request…"/><Button size="sm"><MorphGlyph icon={MessageSquare} size={13}/>Annotate</Button></form></section>}<div className="annotation-list">{annotations.map(a=><article key={a.id} className={a.resolved?'resolved':''}><p>“{a.quoted_text}”</p>{a.note&&<strong>{a.note}</strong>}<div><Button variant="ghost" size="sm" onClick={()=>onResolve(a.id)}><MorphGlyph icon={Check} size={12}/>Resolve</Button><Button variant="ghost" size="icon" onClick={()=>onDelete(a.id)}><MorphGlyph icon={Trash2} size={12}/></Button></div></article>)}{!annotations.length&&<p className="empty">Select text in the visual editor to create an annotation.</p>}</div><section className="job-area"><Button variant="outline" className="wide" onClick={()=>setJobOpen(!jobOpen)}><MorphGlyph icon={jobOpen?ChevronUp:Paperclip} size={14}/>Job description {jobs.length?`(${jobs.length})`:''}</Button>{jobOpen&&<><Textarea value={job} onChange={e=>setJob(e.target.value)} placeholder="Paste a job description…"/><Button className="wide" onClick={()=>{if(job.trim()){onAddJob({title:'Pasted job description',content:job});setJob('');setJobOpen(false)}}}>Save description</Button><label className="upload">or upload TXT, Markdown, or PDF<input type="file" accept=".txt,.md,.pdf" onChange={e=>e.target.files?.[0]&&onAddJob(e.target.files[0])}/></label></>}</section><div className="chat-coming"><span>✦</span><p><strong>AI assistant comes next</strong><br/>Ollama and hosted providers will create reviewable change proposals here.</p></div></aside>
}
